config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users, :controllers => { :omniauth_callbacks => "users/omniauth_callbacks" }
  root 'jobs#index'

  resources :jobs
  resources :profiles


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
	has_attached_file :avatar, styles: { big: "550x800>", medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :avatar, content_type: /\Aimage\/.*\z/
	
	belongs_to :user
    
    validates_presence_of :Titel, :Beschreibung, :Ort

    def self.recent
      order("created_at DESC")
	end

	def self.search(search)
		where('"Ort" ILIKE ? OR "Titel" ILIKE ? OR "Beschreibung" ILIKE ?', "%#{search.downcase}%", "%#{search.downcase}%", "%#{search.downcase}%")
	end
end

app/models/profile.rb
class Profile < ApplicationRecord
	has_attached_file :profileavatar, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/images/:style/missing.png"
    validates_attachment_content_type :profileavatar, content_type: /\Aimage\/.*\z/

	belongs_to :user
	validates_presence_of :Titel, :Beschreibung, :Name
end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:site_admin], multiple: false)                                      ##
  ############################################################################################ 
 

	has_many :jobs
	has_one :profile
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :omniauth_providers => [:facebook]

  def has_profile?
    return false unless profile
    profile.persisted?
  end

  def self.new_with_session(params, session)
  super.tap do |user|
    if data = session["devise.facebook_data"] && session["devise.facebook_data"]["extra"]["raw_info"]
      user.email = data["email"] if user.email.blank?
    end
  end
end

def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
    user.email = auth.info.email
    user.password = Devise.friendly_token[0,20]
    user.name = auth.info.name   # assuming the user model has a name
    user.image = auth.info.image # assuming the user model has an image
  end
end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
	before_action :set_job, only: [:show, :edit, :update, :destroy]
  access all: [:show, :index], user: :all, site_admin: :all
  


	def index
     @jobs = Job.order("created_at DESC").recent.page(params[:page]).per(10)
     @jobs = @jobs.search(params[:search]).order("created_at DESC") if params[:search]
  end

	def new
	  @job = current_user.jobs.build
	end

	def create
      @job = current_user.jobs.build(job_params)
      respond_to do |format|
      if @job.save
        format.html { redirect_to @job, notice: 'Job was successfully created.' }
        format.json { render :show, status: :created, location: @job }
      else
        format.html { render :new }
        format.json { render json: @job.errors, status: :unprocessable_entity }
        flash[:alert] = "Job konnte nicht erstellt werden, bitte alle Felder ausfüllen!"
      end
    end
  end

  def show
	end

	def edit
	end

	def update
	  respond_to do |format|
        if @job.update(job_params)
          format.html { redirect_to @job, notice: 'Job was successfully updated.' }
          format.json { render :show, status: :ok, location: @job }
        else
          format.html { render :edit }
          format.json { render json: @job.errors, status: :unprocessable_entity }
        end
      end
    end

	def destroy
	  @job.destroy
      respond_to do |format|
        format.html { redirect_to jobs_url, notice: 'Job was successfully destroyed.' }
        format.json { head :no_content }
      end
  end

	private

	def job_params
		params.require(:job).permit(:Titel, :Beschreibung, :Ort, :avatar)
	end
    
  def set_job
  	@job = Job.find(params[:id])
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
	before_action :set_profile, only: [:show, :edit, :update, :destroy]
	access all: [:show, :index], user: :all, site_admin: :all
	

    def index
    	@profiles = Profile.all.page(params[:page]).per(10)
    end

	def new
      @profile = Profile.new(user: current_user)
    end

	def create
		@profile = current_user.build_profile(profile_params)
		if @profile.save
			redirect_to @profile
		else
			flash[:notice] = "Das Profil konnte nicht erstellt werden, bitte fülle alle Felder aus!"
			render 'new'
		end
	end

	def show
	end

	def edit
	end

	def update
	  respond_to do |format|
        if @profile.update(profile_params)
          format.html { redirect_to @profile, notice: 'Profile was successfully updated.' }
          format.json { render :show, status: :ok, location: @profile }
        else
          format.html { render :edit }
          format.json { render json: @profile.errors, status: :unprocessable_entity }
        end
      end
    end

	def destroy
	@profile.destroy
	  respond_to do |format|
	  	format.html { redirect_to profiles_url, notice: 'Profile was successfully destroyed.' }
	  	format.json { head :no_content }
	  end
	end

	private

	def profile_params
		params.require(:profile).permit(:Titel, :Beschreibung, :Name, :profileavatar)
	end

	def set_profile
		@profile = Profile.find(params[:id])
	end

	
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    @user = User.from_omniauth(request.env["omniauth.auth"])

    if @user.persisted?
      sign_in_and_redirect @user, :event => :authentication
      set_flash_message(:notice, :success, :kind => "Facebook") if is_navigational_format?
    else
      session["devise.facebook_data"] = request.env["omniauth.auth"]
      redirect_to new_user_registration_url
    end
  end

  def failure
    redirect_to root_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(text)
       renderer = Redcarpet::Render::HTML.new(filter_html: true, hard_wrap: true)
       options = {
      	fenced_code_blocks: true,
      	no_intra_emphasis: true,
      	autolink: true,
      	lax_html_blocks: true,
       }
       Redcarpet::Markdown.new(renderer, options).render(text).html_safe
    end
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/jobs/_form.html.erb
<%= form_for @job, html: { multipart: true } do |j| %>
  <div class="form-group">
    <%= j.label :Titel %>
    <p><%= j.text_field :Titel %></p>
  </div>
  
  <div class="form-group">
    <%= j.label :Beschreibung %>
    <p><%= j.text_area :Beschreibung, rows: 10, cols: 50, maxlength: 800 %></p>
  </div>

  <div class="form-group">
    <%= j.label :Ort %>
    <p><%= j.text_field :Ort %></p>
  </div>

  <div class="form-group">
    <%= j.file_field :avatar %>
  </div>
  
  <hr>
  
  <%= j.submit "Job einstellen" %>
<% end %>

app/views/jobs/edit.html.erb
<div class="row">
  <div class="col-md-2 col-md-offset-5">
  	<h1>Edit</h1>
    <%= render 'form' %>
  </div>
</div>

app/views/jobs/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-lg-8 col-md-10 mx-auto">
      <h1>Alle Jobangebote</h1>
        <p><%= form_tag(jobs_path, :method => "get", id: "search-form") do %>
            <%= text_field_tag :search, params[:search], placeholder: "Jobs durchsuchen" %>
            <%= submit_tag "Suchen", :name => nil %>
          <% end %>
      </p>
      <%= paginate @jobs %>
        <% @jobs.each do |j| %>
          <div class="border-index">
            <h2 class="post-title"><%= link_to j.Titel, job_path(j) %></h2>
            <h4 class="post-subtitle"><%= j.Ort %></h4>
            <p class="post-meta">Posted <%= distance_of_time_in_words(j.created_at, Time.now) %> ago </p>
          </div>
        <% end %>
      <%= paginate @jobs %>
    </div>
  </div>
</div>




  

app/views/jobs/new.html.erb
<div class="container">
  <div class="row">
  	<div class="col-md-8">
      <h2>Neues Jobangebot</h2>
      <%= render 'form' %>
    </div>
  </div>
</div>

app/views/jobs/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6">
	   <h1><%= @job.Titel %><h1>
          <h3>Beschreibung</h3>
             <%= markdown @job.Beschreibung %>
          <h3>Ort</h3>
             <%= @job.Ort %>
		  <% if current_user == @job.user %>
		     <p><%= link_to ' Bearbeiten', edit_job_path, class: "fa fa-pencil-square-o" %>
	         <%= link_to ' Löschen', @blog, method: :delete, data: { confirm: "Sind Sie sicher?" } , class: "fa fa-trash" %>
		     </p>
		  <% end %>
	</div>
	<div class="cold-md-6">
		<div id="myModal" class="modal">
           <span class="close">&times;</span>
           <img class="modal-content" id="img01">
           <div id="caption"></div>
        </div>

        <% if @job.avatar? %>
	         <%= image_tag @job.avatar.url(:big), id:"myImg" %>
		   <% else %>
		     Kein Bild vorhanden!
	       <% end %>

        <script>
		// Get the modal
		var modal = document.getElementById('myModal');

		// Get the image and insert it inside the modal - use its "alt" text as a caption
		var img = document.getElementById('myImg');
		var modalImg = document.getElementById("img01");
		var captionText = document.getElementById("caption");
		img.onclick = function(){
		    modal.style.display = "block";
		    modalImg.src = this.src;
		    captionText.innerHTML = this.alt;
		}

		// Get the <span> element that closes the modal
		var span = document.getElementsByClassName("close")[0];

		// When the user clicks on <span> (x), close the modal
		span.onclick = function() { 
		    modal.style.display = "none";
		}
		</script>
		   
	</div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Braubrett</title>
    <%= csrf_meta_tags %>

    <%= favicon_link_tag 'favicons/favicon.ico' %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
    <script>
       (adsbygoogle = window.adsbygoogle || []).push({
          google_ad_client: "ca-pub-3692447735586413",
          enable_page_level_ads: true
        });
    </script>
  </head>

  <body>

    


    <%= render partial: 'shared/navbar' %>
    <%= render 'shared/sidebar' %>
    <%= render 'shared/footer' %>
    
    <%= yield %>
    
    <%= js add_gritter(flash[:notice] , sticky: false) %>
    <%= js add_gritter(flash[:alert] , sticky: false) %>
  </body>
</html>

app/views/profiles/_form_profile.html.erb
<%= form_for(@profile) do |p| %>
    <div class="form-group">
		<%= p.label :Titel %><br />
		<%= p.text_field :Titel %>
	</div>

    <div class="form-group">
		<%= p.label :Name %><br />
		<%= p.text_field :Name %>
	</div>

	<div class="form-group">
	  <%= p.label :Beschreibung %><br />
	  <%= p.text_area :Beschreibung, rows: 15, cols: 60, maxlength: 800 %> 
	</div>

	<%= p.file_field :profileavatar %>

	<hr>

	<%= p.submit "Profil erstellen" %>
<% end %> 
 

app/views/profiles/edit.html.erb
<div class="container">
	<div class="row">
       <h1>Profil bearbeiten</h1>
       <%= render 'form_profile' %>
   </div>
</div>

app/views/profiles/index.html.erb
<div class="container">
	<div class="row">
		<h1>Alle Profile</h1>
		   <%= paginate @profiles %>
		      <% @profiles.each do |p| %>
		        <h3><%= link_to p.Titel, profile_path(p) %></h3>
		        <hr>
		      <% end %>
		   <%= paginate @profiles %>
    </div>
</div>

app/views/profiles/new.html.erb
<div class="row">
  <div class="col-md-2 col-md-offset-3">
	<h1>Profil erstellen</h1>

	<%= render 'form_profile' %>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="row">
	<div class="container">
		<div class="col-md-6">
           <h1><%= @profile.Name %></h1>
            <% if @profile.profileavatar? %>
		      <%= image_tag @profile.profileavatar.url(:medium) %>
		    <% else %>
		      No attachment available!
		    <% end %>
	    </div>

        <div class="col-md-6">
		  <h2>Titel</h2>
		    <%= @profile.Titel %>
		  <h3>Beschreibung</h3>
		    <%= markdown @profile.Beschreibung %>
		  <h3>Kontaktieren</h3>
		    <%= @profile.user.email %>

          <% if user_signed_in? %>
	          <% if current_user.profile == @profile %>
			    <p><%= link_to ' Bearbeiten', edit_profile_path, class: "fa fa-pencil-square-o" %>
			       <%= link_to ' Löschen', @profile, method: :delete, data: { confirm: "Sind Sie sicher?" }, class: "fa fa-trash" %>
			    </p>
			  <% end %>
		 <% end %>  
		</div>
	</div>
</div>

		 
 

app/views/shared/_footer.html.erb
<div class="navbar navbar-inverse navbar-fixed-bottom" role="navigation">
	<div class="container">
		
		<div class="navbar-text pull-left">
		   <p>&copy; 2018  Mark Billes - All Rights Reserved</p>
		</div>

	</div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-inverse navbar-static-top">
  <div class="container">
    <button class="navbar-toggle" data-toggle="collapse" data-target=".navHeaderCollapse">
  	  <span class="icon-bar"></span>
  	  <span class="icon-bar"></span>
  	  <span class="icon-bar"></span>
  	</button>
  	    
    <div class="collapse navbar-collapse navHeaderCollapse">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to 'Ich suche einen Job', profiles_path %></li>
        <li><%= link_to 'Neues Jobangebot einstellen', new_job_path %></li>
          <% if user_signed_in?  %>
            <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
            <% if current_user.image? %>
              <%= image_tag(current_user.image) %>
            <% end %>
            <% else %>
              <li><%= link_to 'Login', new_user_session_path %>
              <li><%= link_to 'Register', new_user_registration_path %>
          <% end %>
      </ul>
  	</div>
  </div>
</div>

app/views/shared/_sidebar.html.erb
<nav class="navbar navbar-default sidebar" role="navigation">
    <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-sidebar-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>      
    </div>
    <div class="collapse navbar-collapse" id="bs-sidebar-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <%= link_to root_path do %>
          <%= image_tag "Braubrettlogo.png", class: "logo" %>
        <% end %>
        <li class="active"><%= link_to 'Home', root_path %></li>
        <li class="dropdown">
          <% if user_signed_in? %>
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">Mein Profil <span class="caret"></span><span style="font-size:16px;" class="pull-right hidden-xs showopacity glyphicon glyphicon-user"></span></a>
              <ul class="dropdown-menu forAnimate" role="menu">
                <% if current_user.has_profile? %>
                  <li><%= link_to 'Meine Jobsuche', profile_path(current_user.profile) %></li>
                <% else %>
                  <li><%= link_to 'Profil für Jobsuche erstellen' , new_profile_path %></li>
                <% end %>
              </ul>
         <% end %>
        </li>          
      </ul>
    </div>
  </div>
</nav>